name: CI

on:
  push:
    branches:
      - features/*
  pull_request:
    branches:
      - hotfix/*
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        id: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        id: setup
        run: |
          yarn
          yarn lerna run build:tools --parallel
        if: ${{ steps.checkout.outcome == 'success' && steps.node.outcome == 'success' }}

      - name: Execute linting
        run: yarn lerna run lint --parallel
        if: ${{ steps.setup.outcome == 'success' }}

      - name: Execute tests
        run: yarn lerna run test --parallel
        if: ${{ steps.setup.outcome == 'success' }}

